train_data_path: ../2023_data.parquet

features:
  - [pitcher, categorical]
  - [pitch_type, categorical]
  - [release_speed, numeric]

keys:
  - game_pk
  - at_bat_number
  - pitch_number

max_epochs: 10
log_every_n: 30
precision: 16-mixed
hidden_size: 64
lr: 0.001
