train_data_path: ../drive/MyDrive/baseball/2023_data.parquet
processed_data_path: ../drive/MyDrive/baseball/2023_processed.parquet
morpher_path: ../drive/MyDrive/baseball/morphers.yaml

features:
  - [pitcher, categorical]
  - [pitch_type, categorical]
  - [release_speed, numeric]

keys:
  - game_pk
  - at_bat_number
  - pitch_number
