train_data_path: ./data/all_data.parquet

rename:
  type: result_type

features:
  - [pitcher, categorical, {}]
  - [batter, categorical, {}]
  # - [stand, categorical, {}]
  # - [pitch_name, categorical, {}]
  # - [release_speed, numeric, {n_quantiles: 32}]
  # - [pfx_x, numeric, {n_quantiles: 32}]
  # - [pfx_z, numeric, {n_quantiles: 32}]
  # - [plate_x, numeric, {n_quantiles: 32}]
  # - [plate_z, numeric, {n_quantiles: 32}]
  - [description, categorical, {}]
  - [events, categorical, {}]
  - [end_of_at_bat, categorical, {}]
  - [end_of_inning, categorical, {}]
  - [end_of_game, categorical, {}]

# Optionally resume from a checkpoint
checkpoint_path: null
epoch_offset: null

# job
max_length: 384
n_workers: 10
# Multiply by accumulate_batches to get actual rate.
log_every_n: 3

# Network spec
precision: bf16-mixed
hidden_size: 256
tr_args:
  n_layers: 4
  layer_args:
    d_model: 256
    ff_dim: 512
  position_encoding: cope
  attn_args:
    n_q_heads: 8
    n_kv_heads: 8
    cope_args:
      n_positions: 32

# Learning dynamics
max_epochs: 80
lr: 0.0005
batch_size: 64
accumulate_batches: 8