train_data_path: ./data/all_data.parquet

rename:
  type: result_type

features:
  - [pitcher, categorical, {}]
  - [batter, categorical, {}]
  # - [stand, categorical, {}]
  # - [pitch_name, categorical, {}]
  # - [release_speed, numeric, {n_quantiles: 32}]
  # - [pfx_x, numeric, {n_quantiles: 32}]
  # - [pfx_z, numeric, {n_quantiles: 32}]
  # - [plate_x, numeric, {n_quantiles: 32}]
  # - [plate_z, numeric, {n_quantiles: 32}]
  - [result_type, categorical, {}]
  - [events, categorical, {}]
  - [end_of_at_bat, categorical, {}]
  - [end_of_inning, categorical, {}]
  - [end_of_game, categorical, {}]



# job
n_workers: 10
# Multiply by accumulate_batches to get actual rate.
log_every_n: 3

# Network spec
precision: bf16-mixed
hidden_size: 256
tr_args:
  nhead: 8
  dim_feedforward: 512
  dropout: 0.1
  num_layers: 4

# Learning dynamics
max_epochs: 40
lr: 0.0005
batch_size: 128
accumulate_batches: 4