train_data_path: ./data/all_data.parquet

rename:
  type: result_type

keys:
  - game_pk
  - at_bat_number

features:
  - [description, categorical, {}]
  # - [end_of_at_bat, categorical, {}]

# Optionally resume from a checkpoint
checkpoint_path: null
epoch_offset: null

# job
max_length: 20
n_workers: 10
# Multiply by accumulate_batches to get actual rate.
log_every_n: 20

# Network spec
precision: bf16-mixed
hidden_size: 64
tr_args:
  n_layers: 4
  layer_args:
    d_model: 64
    ff_dim: 128
  position_encoding: cope
  attn_args:
    n_q_heads: 8
    n_kv_heads: 8
    cope_args:
      n_positions: 8

# Learning dynamics
max_epochs: 5
lr: 0.0002
batch_size: 4096
accumulate_batches: 1
