train_data_path: ../2023_data.parquet

rename:
  type: result_type

features:
  - [stand, categorical]
  - [pitcher, categorical]
  - [balls, categorical]
  - [strikes, categorical]
  - [pitch_type, categorical]
  - [release_speed, numeric]
  - [pfx_x, numeric]
  - [pfx_z, numeric]
  - [plate_x, numeric]
  - [plate_z, numeric]
  - [result_type, categorical]

context_features:
  - stand
  - pitcher
  - balls
  - strikes

keys:
  - game_pk
  - at_bat_number
  - pitch_number

# job
n_workers: 10
log_every_n: 30
# Network spec
precision: bf16
hidden_size: 256
# Learning dynamics
max_epochs: 30
lr: 0.003
batch_size: 4096
p_dropout: 0.5