train_data_path: ./data/all_data.parquet

rename:
  type: result_type

keys:
  - game_pk
  - at_bat_number

# These are fixed for the whole sequence; we want them in the start of sequence position.
fixed_features:
  - [pitcher_name, categorical, {}]
  - [batter_name, categorical, {}]

# These vary pitch-by-pitch.
features:
  - [pitch_name, categorical, {}]
  - [release_speed, numeric, {n_quantiles: 64}]
  - [plate_x, numeric, {n_quantiles: 64}]
  - [plate_z, numeric, {n_quantiles: 64}]
  - [description, categorical, {}]
  - [end_of_at_bat, categorical, {}]

# Optionally resume from a checkpoint
checkpoint_path: null
epoch_offset: null

# job
max_length: 20
n_workers: 10
# Multiply by accumulate_batches to get actual rate.
log_every_n: 20

# Network spec
precision: bf16-mixed
hidden_size: 256
tr_args:
  n_layers: 4
  layer_args:
    d_model: 256
    ff_dim: 768
  position_encoding: cope
  attn_args:
    n_q_heads: 8
    n_kv_heads: 8
    cope_args:
      n_positions: 8

# Learning dynamics
max_epochs: 25
lr: 0.0002
batch_size: 4096
accumulate_batches: 1
