train_data_path: ../drive/MyDrive/baseball/2023_data.parquet
processed_data_path: ../drive/MyDrive/baseball/2023_processed.parquet
morpher_path: ../drive/MyDrive/baseball/morphers.yaml

features:
  - [pitcher, categorical]
  - [pitch_type, categorical]
  - [release_speed, numeric]

keys:
  - game_pk
  - at_bat_number
  - pitch_number

max_epochs: 3
log_every_n: 30
precision: 16-true
hidden_size: 64
lr: 0.001
